export const NOVO_CONTATO = {
    VISIBLE: 'OPEN_MODAL_NOVO_CONTATO',
    HIDDEN: 'CLOSE_MODAL_NOVO_CONTATO',
}

export const NOVA_EMPRESA = {
    VISIBLE: 'OPEN_MODAL_NOVA_EMPRESA',
    HIDDEN: 'CLOSE_MODAL_NOVA_EMPRESA',
}